### ISSUE TITLE
Add version selection for different table columns

### ISSUE THREAD

**Issue by owenvoke** [HDInnovations/u232-to-unit3d#5]
## Detailed description

See #1

The pass key table column (for trackers) changes over time during the development of `U-232`.

I've checked on the repositories by @Bigjoos and it looks like the table columns are as follows:

- [v1](https://github.com/Bigjoos/U-232-V1) `passkey`
- [v2](https://github.com/Bigjoos/U-232-V2) `passkey`
- [v3](https://github.com/Bigjoos/U-232-V3) `passkey`
- [v4](https://github.com/Bigjoos/U-232-V4) `torrent_pass`
- [v5](https://github.com/Bigjoos/U-232-V5) `torrent_pass`

## Possible implementation

Add a `--version` switch to change between versions.

**Comment by Bigjoos** [comment]
Incorrect, v5 is also torrent_pass, that was done when XBT was introduced to allow end user to switch between XBT and default. Only first three versions use passkey.

**Comment by pxgamer** [comment]
@Bigjoos Cheers.
