### ISSUE TITLE
Hash problem 

### ISSUE THREAD

**Issue by georgee** [HDInnovations/u232-to-unit3d#7]
so i have set it up but it seems like there is an error,in my u232 database the info_hash uses binary and unit3d uses varchar,so when it tries to transfer it it gives an error.

**Comment by HDVinnie** [comment]
the error you received would help....

**Comment by maxpayneovh** [comment]
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\x90\xF3\xC1\x1A\xAE\x8C...' for column 'info_hash' at row 1 (SQL: insert into `torrents` (`info_hash`, `name`, `size`, `description`, `seeders`, `leechers`, `num_file`, `created_at`, `updated_at`) values (
▒▒▒▒▒▒)▒▒'▒;▒"▒ ,
